#! /bin/sh

### BEGIN INIT INFO
# Required-Start:    $remote_fs $syslog
# Required-Stop:     $remote_fs $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
### END INIT INFO

# PATH should only include /usr/* if it runs after the mountnfs.sh script
PATH=/sbin:/usr/sbin:/bin:/usr/bin
NAME=chat
DAEMON=/usr/bin/node
PIDFILE=/var/run/$NAME.pid
RUNFILE=/var/www/$NAME.io/index.js
SCRIPTNAME=/etc/init.d/$NAME

# Function that starts the daemon/service
do_start() {
	sudo start-stop-daemon -Sbmp $PIDFILE -x $DAEMON $RUNFILE
}

# Function that stops the daemon/service
do_stop() {
	sudo start-stop-daemon -Kp $PIDFILE
}

# Router
case "$1" in
  start)
	do_start
	;;
  stop)
	do_stop
	;;
  restart)
	do_stop && do_start
	;;
  *)
	echo "Usage: $SCRIPTNAME {start|stop|restart}" >&2
	exit 1
	;;
esac

exit $?
